version: '3'
services:

  # Oracle service (label used to access the service container)
  oracle:
    # Docker Hub image (feel free to change the tag "latest" to any other available one)
    image: gvenzl/oracle-xe:21.3.0-slim
    restart: unless-stopped
    volumes:
      # - oracle-data:/opt/oracle/oradata
      - ./oracle_db_init.sql:/container-entrypoint-initdb.d/oracle_db_init.sql

    # Provide passwords and other environment variables to container
    environment:
      ORACLE_RANDOM_PASSWORD: true
      # APP_USER: oracle-user
      # APP_USER_PASSWORD: 123456

    ports:
      - 1521:1521
